[2018-11-02T10:42:08.005] [ERROR] Error - {"Error_Name":"Mongodb Connection Error","Error_Address":"Server.js","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [ds249311.mlab.com:49311] on first connect [MongoNetworkError: getaddrinfo EAI_AGAIN ds249311.mlab.com:49311]"}}
[2018-11-02T10:42:08.010] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [ds249311.mlab.com:49311] on first connect [MongoNetworkError: getaddrinfo EAI_AGAIN ds249311.mlab.com:49311]"}}
[2018-11-02T15:47:43.947] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":"Error: Route.post() requires a callback function but got a [object Undefined]"}
[2018-11-02T15:48:13.756] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":"Error: Route.post() requires a callback function but got a [object Undefined]"}
[2018-11-02T17:43:35.468] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":"ReferenceError: multer is not defined"}
[2018-11-02T17:44:13.574] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":"ReferenceError: multer is not defined"}
[2018-11-02T17:47:43.574] [ERROR] Error - {"Error_Name":"Security Error For Every Request Log Creation","Error_Address":"Server.js","Ip":"::1","Request_From_Origin":"http://localhost:4200","Request_From":"http://localhost:4200/Create_Employees","Request_Url":"/Hr/Employee_Create","Request_Body":{},"If_Get":{},"Device_Info":{"ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36","browser":{"name":"Chrome","version":"70.0.3538.77","major":"70"},"engine":{"name":"WebKit","version":"537.36"},"os":{"name":"Windows","version":"10"},"device":{},"cpu":{"architecture":"amd64"}}}
[2018-11-02T18:22:58.588] [ERROR] Error - {"Error_Name":"Mongodb Connection Error","Error_Address":"Server.js","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [ds249311.mlab.com:49311] on first connect [MongoNetworkError: getaddrinfo EAI_AGAIN ds249311.mlab.com:49311]"}}
[2018-11-02T18:22:58.594] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [ds249311.mlab.com:49311] on first connect [MongoNetworkError: getaddrinfo EAI_AGAIN ds249311.mlab.com:49311]"}}
[2018-11-02T18:36:11.002] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":"TypeError: Cannot read property 'AadharDocument' of undefined"}
