[2018-08-11T13:33:52.488] [ERROR] Error - {"Error_Name":"CRM Ticket Data Find Query Error","Error_Address":"Crm_Customers.controller.js","Ip":"::1","Request_From_Origin":"http://localhost:4200","Request_From":"http://localhost:4200/Crm_Tickets_View/5b6c3f1b98fa9c1848c79ca8","Request_Url":"/API/CrmCustomers/CrmTickets_View","Request_Body":{"Info":"U2FsdGVkX19CQTgvLvbXdh1jppp/CDlNFm3URdwlFhra8THOBUF4QsiDwgw2ZWp05Wa2bIHSNaASUGQSN+Xxch5K9VdqPQF71mv+qUxSXr0cFzU+9FilJDdT5fXXHN1vnDbWhtQ3UyxrIAaL8EcQVVl6l5T1vuXx7Pc32S9WxqFwFhCOPzpxXSGdzlB2sdbr"},"If_Get":{},"Device_Info":{"ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36","browser":{"name":"Chrome","version":"68.0.3440.106","major":"68"},"engine":{"name":"WebKit","version":"537.36"},"os":{"name":"Windows","version":"10"},"device":{},"cpu":{"architecture":"amd64"}},"Error_Message":{"name":"MongoError","message":"Topology was destroyed"}}
[2018-08-11T13:33:54.181] [ERROR] Error - {"Error_Name":"CRM Tickets List Find Query Error","Error_Address":"Crm_Customers.controller.js","Ip":"::1","Request_From_Origin":"http://localhost:4200","Request_From":"http://localhost:4200/crm_ticket_list","Request_Url":"/API/CrmCustomers/CrmTickets_List","Request_Body":{"Info":"U2FsdGVkX1+aX+A8LsC3yNaZOV4aTWqjIOB0SQXV02a+51XWEu7WD7AxKN/0jmKy3bIrZ1lWICXtcitBzXwwDGmDJKRfGVwyWhCppjVV9XnvD4syc4W3ZsTeVA9VXdXA"},"If_Get":{},"Device_Info":{"ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36","browser":{"name":"Chrome","version":"68.0.3440.106","major":"68"},"engine":{"name":"WebKit","version":"537.36"},"os":{"name":"Windows","version":"10"},"device":{},"cpu":{"architecture":"amd64"}},"Error_Message":{"name":"MongoError","message":"Topology was destroyed"}}
[2018-08-11T13:34:08.843] [ERROR] Error - {"Error_Name":"Mongodb Connection Error","Error_Address":"Server.js","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [ds249311.mlab.com:49311] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND ds249311.mlab.com ds249311.mlab.com:49311]"}}
[2018-08-11T13:34:08.846] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [ds249311.mlab.com:49311] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND ds249311.mlab.com ds249311.mlab.com:49311]"}}
